/**
 * Renders content/blog/*.md into src/lib/blog-data.ts, and regenerates
 * public/sitemap.xml to match. Run with `npm run blog` after adding or editing
 * a post; `npm run build` runs it first.
 *
 * Why generate rather than parse at request time: on Vercel the serverless
 * bundle does not necessarily carry content/, so reading markdown from disk in
 * a loader is a deploy-time surprise waiting to happen. Baking the HTML into a
 * module makes the article part of the SSR output with no filesystem access and
 * no markdown parser in the client bundle — marked is a devDependency and never
 * ships.
 *
 * Front matter:
 *   ---
 *   title:       required, also the <h1> and the <title>
 *   description: required, the meta description — write it, do not let it be
 *                the first 160 characters of the intro
 *   published:   YYYY-MM-DD
 *   updated:     YYYY-MM-DD, optional
 *   tags:        comma separated, optional
 *   ---
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { marked } from "marked";

const ROOT = new URL("..", import.meta.url).pathname;
const DIR = join(ROOT, "content/blog");
const SITE = "https://dhela.in";

function parseFrontMatter(src, file) {
  const m = src.replace(/\r\n/g, "\n").match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) throw new Error(`${file}: missing front matter`);
  const meta = {};
  for (const line of m[1].split("\n")) {
    const kv = line.match(/^([\w-]+):\s*(.*)$/);
    if (kv) meta[kv[1]] = kv[2].trim();
  }
  for (const k of ["title", "description", "published"]) {
    if (!meta[k]) throw new Error(`${file}: front matter is missing "${k}"`);
  }
  return { meta, body: m[2].trim() };
}

/** Slugged ids on headings, so the table of contents can link into the article. */
const slugify = (s) =>
  s.toLowerCase().replace(/[^\w\s-]/g, "").trim().replace(/\s+/g, "-").slice(0, 60);

marked.use({
  renderer: {
    heading({ tokens, depth }) {
      const text = this.parser.parseInline(tokens);
      const id = slugify(text.replace(/<[^>]+>/g, ""));
      return `<h${depth} id="${id}">${text}</h${depth}>\n`;
    },
    // Outbound links open in a new tab; internal ones must not, or in-page
    // navigation would spawn windows.
    link({ href, title, tokens }) {
      const text = this.parser.parseInline(tokens);
      const external = /^https?:\/\//.test(href) && !href.startsWith(SITE);
      const attrs = external ? ' target="_blank" rel="noreferrer noopener"' : "";
      return `<a href="${href}"${title ? ` title="${title}"` : ""}${attrs}>${text}</a>`;
    },
  },
});

const files = (await readdir(DIR)).filter((f) => f.endsWith(".md")).sort().reverse();
if (!files.length) throw new Error(`no posts in ${DIR}`);

const posts = [];
for (const file of files) {
  const { meta, body } = parseFrontMatter(await readFile(join(DIR, file), "utf8"), file);
  const slug = file.replace(/\.md$/, "").replace(/^\d{4}-\d{2}-\d{2}-/, "");
  const html = marked.parse(body);

  // Reading time from the prose only, at 200 wpm — the number people actually
  // decide on, so it should not count markdown syntax.
  const words = body.replace(/[#*_`>|-]/g, " ").split(/\s+/).filter(Boolean).length;
  const minutes = Math.max(1, Math.round(words / 200));

  // Headings become the table of contents. h2 only: an article whose h3s need
  // listing is really two articles.
  const toc = [...body.matchAll(/^##\s+(.+)$/gm)].map((m) => ({
    id: slugify(m[1].replace(/[*_`]/g, "")),
    text: m[1].replace(/[*_`]/g, "").trim(),
  }));

  posts.push({
    slug, title: meta.title, description: meta.description,
    published: meta.published, updated: meta.updated ?? meta.published,
    tags: meta.tags ? meta.tags.split(",").map((t) => t.trim()).filter(Boolean) : [],
    minutes, words, toc, html,
  });
  console.log(`  ${String(minutes).padStart(2)} min  ${String(words).padStart(4)}w  /blog/${slug}`);
}

const dupes = posts.map(p => p.slug).filter((s, i, a) => a.indexOf(s) !== i);
if (dupes.length) throw new Error(`duplicate slugs: ${dupes.join(", ")}`);

await writeFile(join(ROOT, "src/lib/blog-data.ts"),
`// Generated by scripts/build-blog.mjs — run \`npm run blog\`. Do not edit.
// Source of truth is content/blog/*.md.

export type TocEntry = { id: string; text: string };

export type Post = {
  slug: string;
  title: string;
  description: string;
  published: string;
  updated: string;
  tags: string[];
  minutes: number;
  words: number;
  toc: TocEntry[];
  /** Pre-rendered from markdown at build time; safe to inject. */
  html: string;
};

export const POSTS: Post[] = ${JSON.stringify(posts, null, 2)};

export const bySlug = (slug: string): Post | undefined =>
  POSTS.find((p) => p.slug === slug);
`);
console.log(`\nwrote src/lib/blog-data.ts (${posts.length} posts)`);

// The sitemap has to list the articles or nothing crawls them from the root.
const urls = [
  { loc: `${SITE}/`, priority: "1.0", lastmod: null },
  { loc: `${SITE}/blog`, priority: "0.8", lastmod: posts[0].updated },
  ...posts.map((p) => ({ loc: `${SITE}/blog/${p.slug}`, priority: "0.7", lastmod: p.updated })),
];
await writeFile(join(ROOT, "public/sitemap.xml"),
`<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-blog.mjs. Edit content/blog, not this file. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url>
    <loc>${u.loc}</loc>${u.lastmod ? `\n    <lastmod>${u.lastmod}</lastmod>` : ""}
    <priority>${u.priority}</priority>
  </url>`).join("\n")}
</urlset>
`);
console.log(`wrote public/sitemap.xml (${urls.length} urls)`);
